version: "3.1"
services:

    mysql:
      image: mysql:5.7.23
      container_name: scheduler-mysql
      working_dir: /
      volumes:
        - .:/application
        - c:/mysql/scheduler/:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=scheduler
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
      ports:
        - "33065:3306"
